### ISSUE TITLE
actually functional bee brick

### ISSUE THREAD

**Issue by Yoghurt4C** [Draylar/better-bees#3]
how to:
-limit the bee brick to only house one bee at a time
-do a roll shortly before it's time for bees to come out after the night
-if the roll passes, and there isn't currently a bee inside the bee brick, spawn a bee in front of it (or "inside", not sure which is easier)

**Comment by Shnupbups** [comment]
i was going to make the bee brick just one bee but you said make it the same as the vanilla hive
:irritatered:

**Comment by Yoghurt4C** [comment]
yeah but I see the opportunity to make it a reasonable tradeoff now

**Comment by Yoghurt4C** [comment]
3 days left boys, this needs some kind of resolution so I know how to move forward
